[idrac]
Dell_PowerEdge_R640,   idrac_ip='192.168.201.53',  idrac_user='root',  idrac_password='Orange123#'    
Dell_PowerEdge_7640,   idrac_ip='192.168.201.54',  idrac_user='root',  idrac_password='Orange123#'
# docker_netbox_19216820023 ansible_host=192.168.200.23 

